config/routes.rb
Datapages::Application.routes.draw do

  root 'static_pages#home'
  
  match '/contact',     to: 'static_pages#contact', via: 'get'

  
  comfy_route :cms_admin, :path => '/admin'
  comfy_route :cms, :path => '/', :sitemap => false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "HIE Data Pages"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/HelpPages.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">	
      <h1 class="bottomspace"><%= yield(:pageheading) %></h1>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/_contents.html.erb
<div class="contents">
<ol>
	<% @cms_site.pages.root.children.published.each do |page| %>
	  <li><%= link_to page.label, page.url %>
	    <ol>
	      <% page.children.published.each do |page| %>
	        <li><%= link_to page.label, page.url %></li>
  	      <% end %>
  	    </ol>
  	  </li>
	<% end %>
</ol>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "HIE Data Pages", root_path, class: "navbar-brand"  %>
    </div>
  </div><!-- /.container-fluid -->
    
</nav>

app/views/layouts/_next_previous.html.erb
<div class="row next_previous topspace50">
	  <% next_page = @cms_site.pages.find_by(id:@cms_page.id+1)%>
	  <% previous_page = @cms_site.pages.find_by(id:@cms_page.id-1)%>
	  
      <div class="col-xs-3 col-xs-offset-3 center">	
		  <% if previous_page.present? %>
		    <%= link_to '<< Previous', previous_page.url %>
		  <% end %>
	  </div>
	  <div class="col-xs-3 center">
		  <% if next_page.present? %>
		    <%= link_to 'Next >>', next_page.url %>
		  <% end %>  
      </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <h2 class="bottomspace"><%= yield(:pageheading) %></h2>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<% provide(:pageheading, "Contact Details") %>

<p>For more information please contact Gerard Devine (g.devine@uws.edu.au) </p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<% provide(:pageheading, "HIE Data Pages") %>

<div class="center hero-unit">
  <h2> This is the home page for the HIE Data Pages. </h2>
  
  <p><%= link_to "Help Pages", "/help" %></p>
</div>